### ISSUE TITLE
Implement minimal subset of `error` type

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#167]
This involves:

- support error values
- new type descriptor `error`
- new expression syntax `error(E)`
- `T|error` and `error?` as return values only (including for `main`)
-  `panic E;` statement

Follow ons are
- `check E` , `checkpanic E`  expression #406
- langlib `error:message` function #407

This needs #130.

This would be more useful if we have the `is` operator #144 and unions generally.

**Comment by jclark** [comment]
This would allow us to implement string:fromCodePointInt

**Comment by jclark** [comment]
This will require arrays having an inherent type to distinguish `(any|error)[]` and `any[]`, because this

```
any x = [];
```

creates an array with inherent type `(any|error)[]`.

So we could also add an explicit type `any|error`.

**Comment by jclark** [comment]
I removed `fail`: it's pointless (equivalent to `return`) in the absence on `on fail`.

**Comment by jclark** [comment]
Things to do:

- [x] Runtime support for error values #376 
- [x] BIR ErrorConstructInsn for creating error values #377
- [x] Make panicking use error values #379
- [x] Implement error constructor  #386
- [x] Implement `panic` statement #385
- [x] Add `error` type descriptor #387
- [x] Make type test  `is error` work
- [x] Make type cast `<error>` work
- [x] Allow unions with error
- [x] Make sure `===` works

Related
- Add libbacktrace as third-party library #367
- Add libbacktrace to build system #390
- Snapshot stack when creating error value #46 
- Print out backtrace in error value on panic #6

**Comment by jclark** [comment]
Moved remaining parts into separate issues.
