### ISSUE TITLE
Support multiple modules

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#438]
Goal is to be able to compile programs involving multiple modules.

At this stage, we are not trying to serialize the result of the compilation of a module L for use in a compilation of a module M that imports L.  Rather the compilation of M will need to access the source of the modules it imports (transitively).

Parts of this:

- [x] Change interfaces to front module to allow module being compiled to use imported modules #452
- [x] Support full parsing of import declarations #443
- [x] Compiler driver needs to drive partial compilation of imported modules and their dependencies
- [x] Mangling needs to deal with arbitrary module names #448
- [x] Need to be able reference types/constants from imported modules (not just functions) #471
- [x] Command-line interface to support this #441
- [x] Enhance test suite infrastructure to support this #470
- [x] Update subset docs to explain limitations

Related:

- Backtraces should do demangling #458
- Ensure all error messages include filename (and perhaps module information) #459

**Comment by jclark** [comment]
Front-end interface changes to add:

- front:ModuleInterface represents the public interface to a module as used by an importing module
- front:SourceModule is mutable object that represents ordered list of SourceParts that have been loaded into memory
  - constructed from SourcePart[]
  - can provide a list of all the modules it imports directly
  - can construct a bir:Module and/or a ModuleInterface given a mapping from module-ids to module interfaces

Driver creates a SourceModule, gets its imports and recursively creates SourceModules for those. It then compiles every module (creating a bir:Module and/or a ModuleInterface), ensuring that each module is compiled after all the modules it imports.

**Comment by jclark** [comment]
When we do #402, the LLVM module that is generated by nback for each Ballerina module will include external references to type information.  Each program will then need an init LLVM module that combines the type information for modules in the program and generates definitions to satisfy those references. This init module will in the future also perform tasks such as:

- provide code to take the original command-line arguments from main and turn them into the form required by the main function in the root module
- call the initializer of every module in the right order
- start up listeners

We can potentially combine the init module and the root module into a single LLVM module.

This implies that:

- the result of the compilation of a module by nback includes type information in addition to the LLVM module
- nback be able to generate an init module (or insert the equivalent of an init module into the root module) using type information for all the modules in the program

At this point we are not going to serialize this type information, which means the compiler driver needs to compile all modules of the program.  (When we do serialize it, we may want to put it in a section of the `.o` file.)

**Comment by jclark** [comment]
For this issue, we will have the following limitations

- we only compile imports that are part of the same package (i.e. have the same org and initial module name as root package)
- we will treat the root package as having an empty organization name
- other imports are treated as built-in like now (i.e. we do not go read a .bal file to interpret them)
