### ISSUE TITLE
Implement non-nested closed record types

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#495]
This is similar to #136, but

- we will deal with multiple modules (roughly as described in #402 but for mappings)
- we will implement each type as a LLVM struct with a vtable and use #204 to provide a fast path that bypasses the vtable

In this issue, we will restrict the field types to be the same as what is currently allowed as a member type for arrays and maps (otherwise `e[x]` expressions with e having record type give rise to types that we cannot handle). This restriction will be removed in #571 after #539 has been done.

**Comment by jclark** [comment]
Note that we maintain the restriction that we cannot have a union of a subtype of mapping with anything else: subset 8 does not allow e.g. `map<int>?`; we will similarly not yet allow a union of a closed record with nil or anything else. This means that although we can define a recursive record type, we cannot create an instance of one (because it would be infinite). This means it will not be possible in subset 9 to have a value that both belongs to anydata and has cycles, so we do not yet have to worry about doing `==` on cyclic structures.

**Comment by jclark** [comment]
We need to consider something like this:

```
function foo(record {| string x; int y; |} r, string k, int v) {
   r[k] = v;
}
```

Here r may have the exact bit set, but the assignment can be an inherent type violation.

One could argue that this should be a compile error: you can to convert to `map<string|int>` first, if that's what you really want. But the spec is clear that this is OK.

This means we need a concept of a projection being exact or not.

**Comment by jclark** [comment]
We could probably add intersections of record types, without making things significantly harder, since these arise anyway via conditional type narrowing.

**Comment by jclark** [comment]
An expression `r[s]` where type of r is a record type that has members that are records and type of s is a string will give us a type that is a union including record types, but the subset was not planned to include these.

**Comment by jclark** [comment]
We can get a decent implementation on top of our map implementation, without going to an LLVM struct, just by inserting the fields in sorted order in the constructor. Because our mapping implementation has a separate compact array that is in insertion order, for a closed record type this allows us to determine the index of the field in the compact array at compile time.

Still to be done to achieve correctness for closed records:

- [x] In verifier, check that all required fields are present in constructor (just check number of fields)
- [x] Descriptor needs to specify bitset for each field in sorted order (field name is in the map)
- [x] Call mapping_init_member in sorted order in the constructor (only for closed records)
- [x] In mapping_set, check the type against the descriptor for the specific field
- [x] Implement type cast/type test: need a separate descriptor that includes the field names
- [x] Allow `record` token to start a var decl stmt

Optimization:
- [x] In MappingGet insn, if static type is closed record type, then get by index into the key/value array in the map
- [x] Similarly for MappingSet: can do the test for exactness here (and not in the set by name).

**Comment by jclark** [comment]
Need more tests:

- multiple modules: in particular same type in multiple modules
- long string names
