### ISSUE TITLE
Allow unions to contain subtypes of structured types

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#539]
In subset 9, unions are not allowed to contain subtypes of structured (arrays, maps, records). We only support `any` or `any|error` which contain complete basic types.

This issue is to remove this limitation. The main work is to improve how runtime type checking is done (both type test and type cast): the init module will have tables recording (for mapping and list) which atomic types are subtypes of each SubtypeData (Bdd) along the lines proposed in #402.

Things to do:

- [x] Fix buildHasListType to work like buildHasMapType #580
- [x] In the front end, relax restrictions on accepted types to allow these types (this was done as part of #623)
- [x] Fix semTypeRepr to allow these types
- [x] Change TestType struct to support subtypes of multiple uniform types #614
- [x] Fix buildClearExact not to modify tagged pointers with immediate flag set
- [x] Put a unique id (tid) of inherent type in list/mapping descriptors #615
- [x] Handle list subtypes that are not atomic by precomputing list of tids of inherent types that they contain
- [x] Handle mapping subtypes that are not atomic by precomputing list of tids of inherent types that they contain
- [x] Make exactify use tid
- [x] Make the front-end be able to parse these types when they are in local variable declarations #640
- [x] In front-end, select an inherent type from the contextually expected type based on the fields used in mapping constructor
- [x] Fix the subset definition to accomodate this
- [x] Make sure buildWideRepr is doing to the right thing with unions that includes both a list and a mapping

Future optimizations
* #668
* #669
* #670

**Comment by jclark** [comment]
We should do #580 first.

**Comment by jclark** [comment]
Need be clear about what exactness means for unions with subtypes of both list and mapping. For example, if we have a static type `int[]|map<int>`, can the value have the exact bit set? [Exactness design doc](https://github.com/ballerina-platform/nballerina/blob/main/docs/exact.md) says that's OK and it means that:

- if the value is a list, the inherent type must be exactly `int[]` and
- if the value is a mapping, the inherent type must be exactly `map<int>`

**Comment by jclark** [comment]
We should do #614, #615 first.

**Comment by jclark** [comment]
Closing this with optimizations pushed off to the future.
