### ISSUE TITLE
Update JBUGs for slbeta3

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#550]
Go through all JBUG comments and either:

- if the bug has been fixed, remove the comment and the workaround
- if the bug has not been fixed and does not have a number, file a bug report

**Comment by KavinduZoysa** [comment]
These are the list og JBUGs we need to update. 

- [x] compiler/tests/testBalt.bal: `JBUG: #32575`
- [x] compiler/tests/baltest.bal: `JBUG #31679 should use do`
- [x] compiler/compile.bal: `JBUG gets a bad, sad when done with a query expression`
- [x] compiler/balt.bal: `JBUG: can't use Char gives "'string' value 'x' cannot be converted to 'lang.string:Char'`
- [x] compiler/modules/nback/build.bal: `JBUG #31394 would be better to use shifts for these`
- [x] compiler/modules/nback/build.bal: `JBUG #31753 cast`
- [x] compiler/modules/nback/build.bal: `JBUG <int> cast needed (otherwise result is or'd with 0xFF)`
- [x] compiler/modules/nback/scaffold.bal: `JBUG cast needed #31867`
- [x] compiler/modules/nback/scaffold.bal: `JBUG this goes wrong when you use REPR_VOID as a type as in buildRet`
- [x] compiler/modules/nback/equal.bal: `JBUG cast`
- [x] compiler/modules/types/enumerable.bal: `JBUG: #17977`
- [x] compiler/modules/types/core.bal: `JBUG #31751 bad, sad if UT_OBJECT_RW + 1`
- [x] compiler/modules/front/const.bal: `JBUG toString should not be required`
- [x] compiler/modules/front/codeGen.bal: `JBUG #31311 does not allow `outer` here`
- [x] compiler/modules/front/codeGen.bal: `JBUG #31327 cast`
- [x] compiler/modules/front/codeGen.bal: `JBUG #31327 cast`
- [x] compiler/modules/front/codeGen.bal: `JBUG following line results in bad code`
- [x] compiler/modules/front/codeGen.bal: ``JBUG changing `returns` to `return` makes the parse get a NPE during error recovery``
- [x] compiler/modules/front/codeGen.bal: `JBUG build fails when the order of binding pattern is reversed`
- [x] compiler/modules/front/lib.bal: `JBUG temp variable`
- [x] compiler/modules/front/resolveTypes.bal: `JBUG if this is done with a select, then it gets a bad, sad at runtime if the check gets an error`
- [x] compiler/modules/front/resolveTypes.bal: `JBUG would like to use match patterns here, but #30718 prevents it`
- [x] compiler/modules/front/resolveTypes.bal: ``JBUG temp variable `m` is to avoid compiler bug #30736``
- [x] compiler/modules/front/resolveTypes.bal: ``JBUG temp variable `f` is to avoid compiler bug #30736``
- [x] compiler/modules/front/tests/testConst.bal: `JBUG error if next line uncommented`
- [x] compiler/modules/bir/verify.bal: `JBUG #31749 cast should not be needed`
- [x] compiler/modules/err/err.bal: ``JBUG defining these as `error<Detail> & distinct error` results in these errors not being distinct``
- [x] compiler/modules/print.llvm/llvm.bal: `JBUG issue:#31767`
- [x] compiler/modules/print.llvm/llvm.bal: `JBUG #31776 int cast should not be required`
- [x] compiler/modules/print.llvm/llvm.bal: `JBUG #31777 cast should not be necessary`
- [x] compiler/modules/print.llvm/llvm.bal: `JBUG 31700 incorrect code generated if 32 is in hex`
- [x] compiler/modules/print.llvm/llvm.bal: `JBUG #31776 cast should not be necessary`
- [x] compiler/modules/print.llvm/llvm.bal: `JBUG #31758 type of name[0] is string:Char`
- [x] compiler/modules/print.llvm/llvm.bal: `JBUG issue:#31767`
- [x] compiler/modules/front.syntax/token.bal: `JBUG cannot use string:Char #31668 #31660`
- [x] compiler/modules/front.syntax/token.bal: ``JBUG this avoids bloat that causes `method is too large` errors``
- [x] compiler/modules/front.syntax/astString.bal: ``JBUG error if `===` used instead if `is` ``
- [x] compiler/modules/front.syntax/astString.bal: ``JBUG #31775 `foreach var ch in str` gives wrong ch for some str like "\u{10FFFF}""``
- [x] compiler/modules/front.syntax/ascii.bal: ``JBUG without `int` getting `method is too large` error` ``
- [x] compiler/modules/front.syntax/scan.bal: `But multiple runtime/compile-time JBUGs`
- [x] compiler/modules/front.syntax/scan.bal: `JBUG if this comes before keywords it gets a NPE at module init time`
- [x] compiler/modules/front.syntax/scan.bal: `JBUG #31778 shouldn't need this check, fromCodePointInt should return an error`
- [x] compiler/modules/front.syntax/scan.bal: `JBUG NPE from BIROptimizer.java:159 when inlined`
- [x] compiler/modules/front.syntax/scan.bal: `JBUG when FragCode is byte, error without cast`
- [x] compiler/modules/front.syntax/scan.bal: ``JBUG this avoids bloat that causes `method is too large` errors ``
- [x] compiler/modules/front.syntax/parse.bal: `JBUG cast needed #30734`
- [x] compiler/modules/front.syntax/tests/testParser.bal: `JBUG #31673 can't specify the first type to be "V"|"E"|ect`
- [x] compiler/modules/front.syntax/tests/testParser.bal: ``JBUG ballerina-plugin-vscode/#104 can't use string `\` ``
- [x] compiler/modules/front.syntax/tests/testParser.bal: `JBUG #31444 #31713 #31717 can't write below literals in a simpler way`
- [x] compiler/modules/front.syntax/tests/testParser.bal: `JBUG #31444 #31713 #31717 can't write below literals in a simpler way`

**Comment by jclark** [comment]
Please do this as lots of small pull requests rather than one big one.

**Comment by KavinduZoysa** [comment]
By searching from the issue number, the following issues are identified as unfixed in Swan Lake Beta 3. Edited the above list by removing these entries.

compiler/tests/testBalt.bal: `JBUG #32440 can't use assertNotEqual`
compiler/tests/testBalt.bal: `JBUG #31334 cast` (fixed in beta4)
compiler/tests/testSuite.bal: `JBUG #32615 can't use from-in-from query syntax`
compiler/modules/front.syntax/parseTypeDesc.bal: `JBUG should not need cast #30191`
compiler/modules/front.syntax/tests/testParser.bal: ``JBUG #31988 can't use `suffix ?: ""``
compiler/modules/nback/build.bal: `JBUG #28334 type-descriptor is not needed`
compiler/tests/data/float-singleton2.bal: `JBUG #28334 this is highlighted as an error`
compiler/modules/types/float.bal: `JBUG indexOf does not work with -0 because of #32245`
compiler/modules/types/core.bal: `JBUG #28334 type-descriptor is not needed`
compiler/modules/nback/structure.bal: `JBUG #31681 if I combine these statements into a single from/do, then it gives an assignment required error`
compiler/modules/front/codeGen.bal: `JBUG #31782 cast needed`

**Comment by KavinduZoysa** [comment]
New issues created : 
https://github.com/ballerina-platform/ballerina-lang/issues/33227
https://github.com/ballerina-platform/ballerina-lang/issues/33300
https://github.com/ballerina-platform/ballerina-lang/issues/33301
https://github.com/ballerina-platform/ballerina-lang/issues/33303
https://github.com/ballerina-platform/ballerina-lang/issues/33307
https://github.com/ballerina-platform/ballerina-lang/issues/33309
https://github.com/ballerina-platform/ballerina-lang/issues/33211
https://github.com/ballerina-platform/ballerina-lang/issues/33335
https://github.com/ballerina-platform/ballerina-lang/issues/33341
https://github.com/ballerina-platform/ballerina-lang/issues/33346
https://github.com/ballerina-platform/ballerina-lang/issues/32617
https://github.com/ballerina-platform/ballerina-lang/issues/33394
https://github.com/ballerina-platform/ballerina-lang/issues/33369
https://github.com/ballerina-platform/ballerina-lang/issues/33399
https://github.com/ballerina-platform/ballerina-lang/issues/33446

**Comment by KavinduZoysa** [comment]
@jclark, we can close this issue.
