### ISSUE TITLE
Support open record types

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#573]
This involves:

- [x] supporting record-rest-descriptor #736
- [x] supporting the `record { }` syntax #737
- [x] supporting `anydata` #714  (although from the point of view of the subset we can approximate anydata and don't absolutely need #713)

It requires #571

**Comment by jclark** [comment]
We may also need to distinguish `x["foo"]` and `x.foo` to enforce rules on when `x.foo` is allowed.
