### ISSUE TITLE
Implement subtypes of simple types and string

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#575]
Subtypes of simple types and string includes

- simple type singletons
- string singletons
- integer subtypes (`int:*` and byte)
- string:Char
- unions/intersections of the above

Subtasks

- [x] Support runtime type testing of `boolean` subtypes
- [x] Support runtime type testing of `int` subtypes
- [x] Support runtime type testing of `float` subtypes
- [x] Support runtime type testing of `decimal` subtypes
- [x] #850
- [x] #845
- [x] #168
- [x] #661
- [x] #855

Follow-on issue with optimizations:
* #856

**Comment by jclark** [comment]
Several operations on mappings assume for an expression `m[k]` where m is a mapping, the type of k is either a singleton string or a `string`. This assumption will need to be fixed.

**Comment by jclark** [comment]
Should add a `containsInt` member to UniformSubtype in the runtime.

**Comment by jclark** [comment]
Check how numeric conversions interact with singleton.

If x has type `1|2|3`, what is the type of `<decimal>x`.  `1d|2d|3d` would be workable in this case, but consider applying it to int:Signed32: that would be very hard.  Suspect we only do something special in the singleton case.

**Comment by jclark** [comment]
We need to deal with type tests/casts where the representation is not tagged.

**Comment by jclark** [comment]
Need to check we are getting typing rules right for bitwise operations with integer subtypes.

**Comment by jclark** [comment]
Need to look at exactness when key type is neither singleton nor string.
