### ISSUE TITLE
Implement tuple types

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#576]
Implementing tuples is similar to records except that

- tuples support ordering using relational operators
- we have optimized array implementations

Things to do:

- [x] #891 
- [x] Rework array comparison in backend
- [x] Change ListDesc in runtime and init.bal to support tuples
- [x] Allow tuples in resolve types
- [x] Support in init.bal for type testing tuple types
- [x] Use correct contextually expected type for list constructor members
- [x] #910
- [x] Exactness handling in nback for list get on tuples
- [x] Exactness handling in nback for list set on tuples
- [x] #915
- [x] Make langlib list functions work on tuples (then get rid of arrayMemberType)
- [x] #924
- [x] #946 
- [x] #956

**Comment by manuranga** [comment]
Need to figure out if recursive tuple types can be comparable.
